services:
  # Backend API Service
  - type: web
    name: mida-backend-gpb7
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h

databases:
  - name: mida-postgres
    databaseName: mida_chemical_inventory
    user: mida_user
    plan: free